[2023-02-14 16:14:08,668] {scheduler_job.py:182} INFO - Started process (PID=1730) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:14:08,669] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:14:08,670] {logging_mixin.py:104} INFO - [2023-02-14 16:14:08,670] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:14:08,673] {logging_mixin.py:104} INFO - [2023-02-14 16:14:08,672] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:14:08,674] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:14:08,688] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-14 16:14:39,175] {scheduler_job.py:182} INFO - Started process (PID=1792) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:14:39,176] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:14:39,176] {logging_mixin.py:104} INFO - [2023-02-14 16:14:39,176] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:14:39,178] {logging_mixin.py:104} INFO - [2023-02-14 16:14:39,178] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:14:39,179] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:14:39,195] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-14 16:15:09,984] {scheduler_job.py:182} INFO - Started process (PID=1844) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:15:09,985] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:15:09,986] {logging_mixin.py:104} INFO - [2023-02-14 16:15:09,985] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:15:09,988] {logging_mixin.py:104} INFO - [2023-02-14 16:15:09,987] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:15:09,988] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:15:10,004] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-14 16:15:40,526] {scheduler_job.py:182} INFO - Started process (PID=1907) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:15:40,527] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:15:40,527] {logging_mixin.py:104} INFO - [2023-02-14 16:15:40,527] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:15:40,529] {logging_mixin.py:104} INFO - [2023-02-14 16:15:40,528] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:15:40,529] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:15:40,543] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-14 16:16:11,005] {scheduler_job.py:182} INFO - Started process (PID=1959) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:16:11,008] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:16:11,008] {logging_mixin.py:104} INFO - [2023-02-14 16:16:11,008] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:16:11,011] {logging_mixin.py:104} INFO - [2023-02-14 16:16:11,010] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:16:11,011] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:16:11,025] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2023-02-14 16:16:41,422] {scheduler_job.py:182} INFO - Started process (PID=2021) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:16:41,423] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:16:41,423] {logging_mixin.py:104} INFO - [2023-02-14 16:16:41,423] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:16:41,426] {logging_mixin.py:104} INFO - [2023-02-14 16:16:41,425] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:16:41,426] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:16:41,442] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-14 16:17:11,789] {scheduler_job.py:182} INFO - Started process (PID=2073) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:17:11,790] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:17:11,791] {logging_mixin.py:104} INFO - [2023-02-14 16:17:11,790] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:17:11,793] {logging_mixin.py:104} INFO - [2023-02-14 16:17:11,792] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:17:11,793] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:17:11,807] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-14 16:17:42,099] {scheduler_job.py:182} INFO - Started process (PID=2135) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:17:42,100] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:17:42,101] {logging_mixin.py:104} INFO - [2023-02-14 16:17:42,101] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:17:42,103] {logging_mixin.py:104} INFO - [2023-02-14 16:17:42,102] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:17:42,103] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:17:42,118] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-14 16:18:12,533] {scheduler_job.py:182} INFO - Started process (PID=2187) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:18:12,534] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:18:12,534] {logging_mixin.py:104} INFO - [2023-02-14 16:18:12,534] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:18:12,537] {logging_mixin.py:104} INFO - [2023-02-14 16:18:12,536] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:18:12,537] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:18:12,553] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-14 16:18:42,962] {scheduler_job.py:182} INFO - Started process (PID=2249) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:18:42,962] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:18:42,963] {logging_mixin.py:104} INFO - [2023-02-14 16:18:42,963] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:18:42,965] {logging_mixin.py:104} INFO - [2023-02-14 16:18:42,965] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:18:42,965] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:18:42,982] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2023-02-14 16:19:13,424] {scheduler_job.py:182} INFO - Started process (PID=2301) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:19:13,425] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:19:13,426] {logging_mixin.py:104} INFO - [2023-02-14 16:19:13,426] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:19:13,428] {logging_mixin.py:104} INFO - [2023-02-14 16:19:13,428] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:19:13,429] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:19:13,443] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-14 16:19:43,863] {scheduler_job.py:182} INFO - Started process (PID=2363) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:19:43,864] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:19:43,864] {logging_mixin.py:104} INFO - [2023-02-14 16:19:43,864] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:19:43,866] {logging_mixin.py:104} INFO - [2023-02-14 16:19:43,865] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:19:43,866] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:19:43,880] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-14 16:20:14,294] {scheduler_job.py:182} INFO - Started process (PID=2424) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:20:14,295] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:20:14,296] {logging_mixin.py:104} INFO - [2023-02-14 16:20:14,296] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:20:14,298] {logging_mixin.py:104} INFO - [2023-02-14 16:20:14,297] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:20:14,298] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:20:14,324] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.032 seconds
[2023-02-14 16:20:44,680] {scheduler_job.py:182} INFO - Started process (PID=2477) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:20:44,681] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:20:44,681] {logging_mixin.py:104} INFO - [2023-02-14 16:20:44,681] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:20:44,684] {logging_mixin.py:104} INFO - [2023-02-14 16:20:44,683] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:20:44,684] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:20:44,699] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-14 16:21:15,240] {scheduler_job.py:182} INFO - Started process (PID=2539) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:21:15,241] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:21:15,242] {logging_mixin.py:104} INFO - [2023-02-14 16:21:15,242] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:21:15,244] {logging_mixin.py:104} INFO - [2023-02-14 16:21:15,243] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:21:15,244] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:21:15,259] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-14 16:21:45,375] {scheduler_job.py:182} INFO - Started process (PID=2591) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:21:45,376] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:21:45,376] {logging_mixin.py:104} INFO - [2023-02-14 16:21:45,376] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:21:45,378] {logging_mixin.py:104} INFO - [2023-02-14 16:21:45,378] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:21:45,379] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:21:45,392] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-14 16:22:15,604] {scheduler_job.py:182} INFO - Started process (PID=2643) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:22:15,605] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:22:15,606] {logging_mixin.py:104} INFO - [2023-02-14 16:22:15,606] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:22:15,608] {logging_mixin.py:104} INFO - [2023-02-14 16:22:15,607] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:22:15,608] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:22:15,623] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-14 16:22:46,056] {scheduler_job.py:182} INFO - Started process (PID=2705) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:22:46,056] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:22:46,057] {logging_mixin.py:104} INFO - [2023-02-14 16:22:46,057] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:22:46,059] {logging_mixin.py:104} INFO - [2023-02-14 16:22:46,058] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:22:46,059] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:22:46,074] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-14 16:23:16,361] {scheduler_job.py:182} INFO - Started process (PID=2757) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:23:16,362] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:23:16,362] {logging_mixin.py:104} INFO - [2023-02-14 16:23:16,362] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:23:16,365] {logging_mixin.py:104} INFO - [2023-02-14 16:23:16,364] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:23:16,365] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:23:16,379] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-14 16:23:46,636] {scheduler_job.py:182} INFO - Started process (PID=2819) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:23:46,637] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:23:46,637] {logging_mixin.py:104} INFO - [2023-02-14 16:23:46,637] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:23:46,640] {logging_mixin.py:104} INFO - [2023-02-14 16:23:46,639] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:23:46,640] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:23:46,654] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-14 16:24:17,011] {scheduler_job.py:182} INFO - Started process (PID=2880) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:24:17,012] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:24:17,013] {logging_mixin.py:104} INFO - [2023-02-14 16:24:17,013] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:24:17,015] {logging_mixin.py:104} INFO - [2023-02-14 16:24:17,014] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:24:17,015] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:24:17,029] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-14 16:24:47,407] {scheduler_job.py:182} INFO - Started process (PID=2933) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:24:47,408] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:24:47,408] {logging_mixin.py:104} INFO - [2023-02-14 16:24:47,408] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:24:47,411] {logging_mixin.py:104} INFO - [2023-02-14 16:24:47,410] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:24:47,411] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:24:47,427] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2023-02-14 16:25:17,802] {scheduler_job.py:182} INFO - Started process (PID=2992) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:25:17,803] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:25:17,803] {logging_mixin.py:104} INFO - [2023-02-14 16:25:17,803] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:25:17,805] {logging_mixin.py:104} INFO - [2023-02-14 16:25:17,805] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:25:17,806] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:25:17,821] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-14 16:25:48,280] {scheduler_job.py:182} INFO - Started process (PID=3047) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:25:48,281] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:25:48,282] {logging_mixin.py:104} INFO - [2023-02-14 16:25:48,282] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:25:48,285] {logging_mixin.py:104} INFO - [2023-02-14 16:25:48,284] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:25:48,286] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:25:48,305] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.028 seconds
[2023-02-14 16:26:18,699] {scheduler_job.py:182} INFO - Started process (PID=3108) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:26:18,700] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:26:18,701] {logging_mixin.py:104} INFO - [2023-02-14 16:26:18,701] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:26:18,703] {logging_mixin.py:104} INFO - [2023-02-14 16:26:18,702] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:26:18,703] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:26:18,718] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-14 16:26:48,750] {scheduler_job.py:182} INFO - Started process (PID=3161) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:26:48,751] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:26:48,752] {logging_mixin.py:104} INFO - [2023-02-14 16:26:48,752] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:26:48,755] {logging_mixin.py:104} INFO - [2023-02-14 16:26:48,754] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:26:48,755] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:26:48,771] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2023-02-14 16:27:18,926] {scheduler_job.py:182} INFO - Started process (PID=3213) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:27:18,926] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:27:18,927] {logging_mixin.py:104} INFO - [2023-02-14 16:27:18,927] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:27:18,929] {logging_mixin.py:104} INFO - [2023-02-14 16:27:18,928] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:27:18,929] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:27:18,943] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-14 16:27:49,306] {scheduler_job.py:182} INFO - Started process (PID=3275) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:27:49,306] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:27:49,307] {logging_mixin.py:104} INFO - [2023-02-14 16:27:49,307] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:27:49,309] {logging_mixin.py:104} INFO - [2023-02-14 16:27:49,309] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:27:49,309] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:27:49,325] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-14 16:28:19,740] {scheduler_job.py:182} INFO - Started process (PID=3336) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:28:19,741] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:28:19,742] {logging_mixin.py:104} INFO - [2023-02-14 16:28:19,742] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:28:19,745] {logging_mixin.py:104} INFO - [2023-02-14 16:28:19,744] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:28:19,746] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:28:19,764] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.027 seconds
[2023-02-14 16:28:50,233] {scheduler_job.py:182} INFO - Started process (PID=3389) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:28:50,233] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:28:50,234] {logging_mixin.py:104} INFO - [2023-02-14 16:28:50,234] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:28:50,236] {logging_mixin.py:104} INFO - [2023-02-14 16:28:50,235] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:28:50,237] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:28:50,251] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-14 16:29:20,797] {scheduler_job.py:182} INFO - Started process (PID=3447) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:29:20,798] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:29:20,799] {logging_mixin.py:104} INFO - [2023-02-14 16:29:20,798] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:29:20,801] {logging_mixin.py:104} INFO - [2023-02-14 16:29:20,800] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:29:20,801] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:29:20,815] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-14 16:29:51,136] {scheduler_job.py:182} INFO - Started process (PID=3503) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:29:51,137] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:29:51,137] {logging_mixin.py:104} INFO - [2023-02-14 16:29:51,137] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:29:51,140] {logging_mixin.py:104} INFO - [2023-02-14 16:29:51,139] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:29:51,140] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:29:51,155] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-14 16:30:21,665] {scheduler_job.py:182} INFO - Started process (PID=3565) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:30:21,666] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:30:21,666] {logging_mixin.py:104} INFO - [2023-02-14 16:30:21,666] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:30:21,669] {logging_mixin.py:104} INFO - [2023-02-14 16:30:21,668] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:30:21,669] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:30:21,684] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-14 16:30:52,387] {scheduler_job.py:182} INFO - Started process (PID=3617) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:30:52,388] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:30:52,389] {logging_mixin.py:104} INFO - [2023-02-14 16:30:52,389] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:30:52,394] {logging_mixin.py:104} INFO - [2023-02-14 16:30:52,391] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:30:52,394] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:30:52,413] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.029 seconds
[2023-02-14 16:31:22,693] {scheduler_job.py:182} INFO - Started process (PID=3678) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:31:22,694] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:31:22,695] {logging_mixin.py:104} INFO - [2023-02-14 16:31:22,695] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:31:22,698] {logging_mixin.py:104} INFO - [2023-02-14 16:31:22,697] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:31:22,698] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:31:22,712] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-14 16:31:53,254] {scheduler_job.py:182} INFO - Started process (PID=3731) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:31:53,255] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:31:53,256] {logging_mixin.py:104} INFO - [2023-02-14 16:31:53,255] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:31:53,259] {logging_mixin.py:104} INFO - [2023-02-14 16:31:53,257] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:31:53,259] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:31:53,277] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.025 seconds
[2023-02-14 16:32:23,867] {scheduler_job.py:182} INFO - Started process (PID=3783) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:32:23,868] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:32:23,868] {logging_mixin.py:104} INFO - [2023-02-14 16:32:23,868] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:32:23,870] {logging_mixin.py:104} INFO - [2023-02-14 16:32:23,870] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:32:23,870] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:32:23,885] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-14 16:32:54,149] {scheduler_job.py:182} INFO - Started process (PID=3846) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:32:54,150] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:32:54,151] {logging_mixin.py:104} INFO - [2023-02-14 16:32:54,151] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:32:54,153] {logging_mixin.py:104} INFO - [2023-02-14 16:32:54,152] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:32:54,153] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:32:54,167] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-14 16:33:24,460] {scheduler_job.py:182} INFO - Started process (PID=3898) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:33:24,461] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:33:24,461] {logging_mixin.py:104} INFO - [2023-02-14 16:33:24,461] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:33:24,463] {logging_mixin.py:104} INFO - [2023-02-14 16:33:24,463] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:33:24,463] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:33:24,476] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.018 seconds
[2023-02-14 16:33:54,940] {scheduler_job.py:182} INFO - Started process (PID=3960) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:33:54,941] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:33:54,942] {logging_mixin.py:104} INFO - [2023-02-14 16:33:54,941] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:33:54,944] {logging_mixin.py:104} INFO - [2023-02-14 16:33:54,943] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:33:54,945] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:33:54,962] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.025 seconds
[2023-02-14 16:34:25,662] {scheduler_job.py:182} INFO - Started process (PID=4012) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:34:25,663] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:34:25,664] {logging_mixin.py:104} INFO - [2023-02-14 16:34:25,664] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:34:25,666] {logging_mixin.py:104} INFO - [2023-02-14 16:34:25,665] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:34:25,666] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:34:25,680] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-14 16:34:55,933] {scheduler_job.py:182} INFO - Started process (PID=4074) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:34:55,934] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:34:55,935] {logging_mixin.py:104} INFO - [2023-02-14 16:34:55,935] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:34:55,937] {logging_mixin.py:104} INFO - [2023-02-14 16:34:55,937] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:34:55,938] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:34:55,952] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-14 16:35:26,336] {scheduler_job.py:182} INFO - Started process (PID=4126) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:35:26,337] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:35:26,337] {logging_mixin.py:104} INFO - [2023-02-14 16:35:26,337] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:35:26,340] {logging_mixin.py:104} INFO - [2023-02-14 16:35:26,339] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:35:26,340] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:35:26,357] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.024 seconds
[2023-02-14 16:35:56,534] {scheduler_job.py:182} INFO - Started process (PID=4188) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:35:56,535] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:35:56,536] {logging_mixin.py:104} INFO - [2023-02-14 16:35:56,536] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:35:56,538] {logging_mixin.py:104} INFO - [2023-02-14 16:35:56,538] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:35:56,538] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:35:56,552] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-14 16:36:27,210] {scheduler_job.py:182} INFO - Started process (PID=4240) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:36:27,211] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:36:27,211] {logging_mixin.py:104} INFO - [2023-02-14 16:36:27,211] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:36:27,214] {logging_mixin.py:104} INFO - [2023-02-14 16:36:27,213] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:36:27,214] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:36:27,230] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-14 16:36:57,802] {scheduler_job.py:182} INFO - Started process (PID=4302) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:36:57,803] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:36:57,804] {logging_mixin.py:104} INFO - [2023-02-14 16:36:57,804] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:36:57,806] {logging_mixin.py:104} INFO - [2023-02-14 16:36:57,806] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:36:57,807] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:36:57,822] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2023-02-14 16:37:28,061] {scheduler_job.py:182} INFO - Started process (PID=4354) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:37:28,061] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:37:28,062] {logging_mixin.py:104} INFO - [2023-02-14 16:37:28,062] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:37:28,064] {logging_mixin.py:104} INFO - [2023-02-14 16:37:28,063] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:37:28,064] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:37:28,079] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-14 16:37:58,224] {scheduler_job.py:182} INFO - Started process (PID=4416) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:37:58,225] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:37:58,225] {logging_mixin.py:104} INFO - [2023-02-14 16:37:58,225] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:37:58,227] {logging_mixin.py:104} INFO - [2023-02-14 16:37:58,227] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:37:58,228] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:37:58,242] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-14 16:38:29,151] {scheduler_job.py:182} INFO - Started process (PID=4468) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:38:29,151] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:38:29,152] {logging_mixin.py:104} INFO - [2023-02-14 16:38:29,152] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:38:29,154] {logging_mixin.py:104} INFO - [2023-02-14 16:38:29,154] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:38:29,154] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:38:29,171] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2023-02-14 16:38:59,877] {scheduler_job.py:182} INFO - Started process (PID=4530) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:38:59,878] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:38:59,879] {logging_mixin.py:104} INFO - [2023-02-14 16:38:59,878] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:38:59,881] {logging_mixin.py:104} INFO - [2023-02-14 16:38:59,881] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:38:59,881] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:38:59,896] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-14 16:39:30,073] {scheduler_job.py:182} INFO - Started process (PID=4582) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:39:30,074] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:39:30,074] {logging_mixin.py:104} INFO - [2023-02-14 16:39:30,074] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:39:30,077] {logging_mixin.py:104} INFO - [2023-02-14 16:39:30,076] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:39:30,077] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:39:30,092] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.022 seconds
[2023-02-14 16:40:00,460] {scheduler_job.py:182} INFO - Started process (PID=4644) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:40:00,462] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:40:00,462] {logging_mixin.py:104} INFO - [2023-02-14 16:40:00,462] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:40:00,465] {logging_mixin.py:104} INFO - [2023-02-14 16:40:00,464] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:40:00,465] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:40:00,481] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.023 seconds
[2023-02-14 16:40:31,220] {scheduler_job.py:182} INFO - Started process (PID=4696) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:40:31,221] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:40:31,222] {logging_mixin.py:104} INFO - [2023-02-14 16:40:31,221] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:40:31,224] {logging_mixin.py:104} INFO - [2023-02-14 16:40:31,223] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:40:31,224] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:40:31,238] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
[2023-02-14 16:41:01,792] {scheduler_job.py:182} INFO - Started process (PID=4757) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:41:01,793] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:41:01,794] {logging_mixin.py:104} INFO - [2023-02-14 16:41:01,793] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:41:01,797] {logging_mixin.py:104} INFO - [2023-02-14 16:41:01,797] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:41:01,798] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:41:01,823] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.035 seconds
[2023-02-14 16:41:32,118] {scheduler_job.py:182} INFO - Started process (PID=4809) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:41:32,125] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:41:32,126] {logging_mixin.py:104} INFO - [2023-02-14 16:41:32,126] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:41:32,130] {logging_mixin.py:104} INFO - [2023-02-14 16:41:32,129] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:41:32,155] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:41:32,181] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.082 seconds
[2023-02-14 16:42:02,311] {scheduler_job.py:182} INFO - Started process (PID=4871) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:42:02,312] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:42:02,312] {logging_mixin.py:104} INFO - [2023-02-14 16:42:02,312] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:42:02,314] {logging_mixin.py:104} INFO - [2023-02-14 16:42:02,314] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:42:02,315] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:42:02,328] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-14 16:42:32,436] {scheduler_job.py:182} INFO - Started process (PID=4918) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:42:32,437] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:42:32,437] {logging_mixin.py:104} INFO - [2023-02-14 16:42:32,437] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:42:32,439] {logging_mixin.py:104} INFO - [2023-02-14 16:42:32,439] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:42:32,440] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:42:32,455] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-14 16:43:02,944] {scheduler_job.py:182} INFO - Started process (PID=4979) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:43:02,946] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:43:02,947] {logging_mixin.py:104} INFO - [2023-02-14 16:43:02,947] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:43:02,950] {logging_mixin.py:104} INFO - [2023-02-14 16:43:02,949] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:43:02,951] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:43:02,972] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.031 seconds
[2023-02-14 16:43:33,429] {scheduler_job.py:182} INFO - Started process (PID=5032) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:43:33,430] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:43:33,430] {logging_mixin.py:104} INFO - [2023-02-14 16:43:33,430] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:43:33,432] {logging_mixin.py:104} INFO - [2023-02-14 16:43:33,432] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:43:33,433] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:43:33,446] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.019 seconds
[2023-02-14 16:44:04,109] {scheduler_job.py:182} INFO - Started process (PID=5084) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:44:04,110] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:44:04,111] {logging_mixin.py:104} INFO - [2023-02-14 16:44:04,111] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:44:04,115] {logging_mixin.py:104} INFO - [2023-02-14 16:44:04,113] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:44:04,115] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:44:04,194] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.088 seconds
[2023-02-14 16:44:34,219] {scheduler_job.py:182} INFO - Started process (PID=5136) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:44:34,293] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:44:34,294] {logging_mixin.py:104} INFO - [2023-02-14 16:44:34,293] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:44:34,297] {logging_mixin.py:104} INFO - [2023-02-14 16:44:34,296] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:44:34,297] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:44:34,317] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.101 seconds
[2023-02-14 16:45:04,905] {scheduler_job.py:182} INFO - Started process (PID=5188) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:45:04,906] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:45:04,906] {logging_mixin.py:104} INFO - [2023-02-14 16:45:04,906] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:45:04,909] {logging_mixin.py:104} INFO - [2023-02-14 16:45:04,908] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:45:04,909] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:45:04,923] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.021 seconds
[2023-02-14 16:45:35,825] {scheduler_job.py:182} INFO - Started process (PID=5250) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:45:35,825] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:45:35,826] {logging_mixin.py:104} INFO - [2023-02-14 16:45:35,826] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:45:35,828] {logging_mixin.py:104} INFO - [2023-02-14 16:45:35,828] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:45:35,829] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:45:35,873] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.051 seconds
[2023-02-14 16:46:06,637] {scheduler_job.py:182} INFO - Started process (PID=5302) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:46:06,638] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:46:06,639] {logging_mixin.py:104} INFO - [2023-02-14 16:46:06,638] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:46:06,642] {logging_mixin.py:104} INFO - [2023-02-14 16:46:06,641] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:46:06,642] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:46:06,659] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.025 seconds
[2023-02-14 16:46:37,474] {scheduler_job.py:182} INFO - Started process (PID=5364) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:46:37,476] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:46:37,476] {logging_mixin.py:104} INFO - [2023-02-14 16:46:37,476] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:46:37,479] {logging_mixin.py:104} INFO - [2023-02-14 16:46:37,478] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:46:37,479] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:46:37,495] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.024 seconds
[2023-02-14 16:47:07,863] {scheduler_job.py:182} INFO - Started process (PID=5416) to work on /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:47:07,863] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_airbyte_dbt.py for tasks to queue
[2023-02-14 16:47:07,864] {logging_mixin.py:104} INFO - [2023-02-14 16:47:07,864] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:47:07,866] {logging_mixin.py:104} INFO - [2023-02-14 16:47:07,866] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_airbyte_dbt.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_airbyte_dbt.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2023-02-14 16:47:07,867] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_airbyte_dbt.py
[2023-02-14 16:47:07,880] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_airbyte_dbt.py took 0.020 seconds
